# Hello in GrepoBot!
# Remember to change the correct values in the config.yaml file

# GrepoBot configuration file

round_time: 60           # Time in seconds between each round of actions
rounds: 320              # Total number of rounds to be executed
 
# What comes after each other is important!
actions:                 # List of actions to be performed by Grepobot
  # - Reload
  - LogIn
  - SolveCaptcha
  - GetResources
  - CloseAll
